# Generated by Django 5.0.1 on 2024-01-12 03:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="name",
            new_name="fullname",
        ),
    ]
