# Generated by Django 5.0.1 on 2024-01-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_rename_name_order_fullname"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total",
            field=models.FloatField(default="1"),
            preserve_default=False,
        ),
    ]
