# Generated by Django 5.0.1 on 2024-01-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="profilepic.png", upload_to="profile_pictures"
            ),
        ),
    ]
