# Generated by Django 5.0.1 on 2024-01-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_moviedata_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="moviedata",
            name="image",
            field=models.ImageField(
                default="Images/None/Noimg.png", upload_to="Images/"
            ),
        ),
    ]
