# Generated by Django 5.0.1 on 2024-01-15 02:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pdf", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="previous_work",
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="profile",
            name="skills",
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="profile",
            name="summary",
            field=models.TextField(max_length=2000),
        ),
    ]
